name: 'Prevent main from untested code'

on:
  push:
    branches: [ "main", "master", "develop", "release/**" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
      runs-on: ubuntu-latest 
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build and test Docker image
        run: | 
          docker build --target test -f Dockerfile -t internal-source-extract:test . --no-cache
          docker run --rm internal-source-extract:test

  # Publish artifact for production only on main  
  publish-artifact:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build production Docker image
      run: docker build --target runtime -t internal-source-extract:latest .

    - name: Save Docker image to tar file
      run: docker save -o internal-source-extract.tar internal-source-extract:latest

    - name: Upload Docker image tar file
      uses: actions/upload-artifact@v4
      with:
        name: internal-source-extract-tar
        path: internal-source-extract.tar
